name: Flutter CI

on:
  push:
    branches: [FerMod-CI]
  pull_request:
    branches: [FerMod-CI]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    container:
      image: google/dart:latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
      - name: Install dependencies
      - run: flutter pub get
      - name: Run tests
      - run: flutter test
      # - name: Push APK to Releases
      #   uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: "build/app/outputs/apk/debug/*.apk"
      #     token: ${{ secrets.GITHUB_TOKEN }}
## Example
# on: push
# name: Test, Build and Release apk
# jobs:
#   build:
#     name: Build APK
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v1
#     - uses: actions/setup-java@v1
#       with:
#         java-version: '12.x'
#     - uses: subosito/flutter-action@v1
#       with:
#         flutter-version: '1.7.8+hotfix.4'
#     - run: flutter pub get
#     - run: flutter test
#     - run: flutter build apk --debug --split-per-abi
#     - name: Push APK to Releases
#       uses: ncipollo/release-action@v1
#       with:
#         artifacts: "build/app/outputs/apk/debug/*.apk"
#         token: ${{ secrets.TOKEN }}
